language: android
android:
  components:
    - build-tools-18.1.0

before_script:
  # Create and start emulator
  - echo no | android create avd --force -n test -t android-16 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - ./wait_for_emulator
  - unset TRAVIS
  - wget http://www.deflaker.org/maven/apache-maven-3.3.9.zip
  - unzip -qq apache-maven-3.3.9.zip
  - export M2_HOME=$PWD/apache-maven-3.3.9
  - export PATH=$M2_HOME/bin:$PATH

script: mvn verify -B -Pintegration-tests -Dandroid.device=test
# script: mvn install -Pintegration-tests -Dandroid.device=test


jdk: oraclejdk8
env:
  global:
    - FIREBASE_KEY=AIzaSyDU7I6pnN322BvRNN24jRX52owAvuHH1K4 
    - MAVEN_OPTS="-Xmx3g" 
    - JAVA_OPTS="'-Xms512m -Xmx3g'"
install: true
# script: mvn -B verify
